# Generated by Django 4.2.15 on 2025-09-03 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='age',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('housewife', 'Housewife'), ('service_government', 'Service–Government'), ('service_private', 'Service–Private'), ('business_self_employed', 'Business-Self-Employed'), ('farmer', 'Farmer'), ('labour_worker', 'Labour-Worker'), ('doctor', 'Doctor'), ('engineer', 'Engineer'), ('lawyer', 'Lawyer'), ('ca', 'CA'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], default='other', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
